export const getExampleRecipeInfo = () => {
  return {
    id: 716429,
    title: "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs",
    image: "https://spoonacular.com/recipeImages/716429-556x370.jpg",
    imageType: "jpg",
    servings: 2,
    readyInMinutes: 45,
    license: "CC BY-SA 3.0",
    sourceName: "Full Belly Sisters",
    sourceUrl:
      "http://fullbellysisters.blogspot.com/2012/06/pasta-with-garlic-scallions-cauliflower.html",
    spoonacularSourceUrl:
      "https://spoonacular.com/pasta-with-garlic-scallions-cauliflower-breadcrumbs-716429",
    aggregateLikes: 209,
    healthScore: 19.0,
    spoonacularScore: 83.0,
    pricePerServing: 163.15,
    analyzedInstructions: [],
    cheap: false,
    creditsText: "Full Belly Sisters",
    cuisines: [],
    dairyFree: false,
    diets: [],
    gaps: "no",
    glutenFree: false,
    instructions: "",
    ketogenic: false,
    lowFodmap: false,
    occasions: [],
    sustainable: false,
    vegan: false,
    vegetarian: false,
    veryHealthy: false,
    veryPopular: false,
    whole30: false,
    weightWatcherSmartPoints: 17,
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    extendedIngredients: [
      {
        aisle: "Milk, Eggs, Other Dairy",
        amount: 1.0,
        consitency: "solid",
        id: 1001,
        image: "butter-sliced.jpg",
        measures: {
          metric: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
          us: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
        },
        meta: [],
        name: "butter",
        original: "1 tbsp butter",
        originalName: "butter",
        unit: "tbsp",
      },
      {
        aisle: "Produce",
        amount: 2.0,
        consitency: "solid",
        id: 10011135,
        image: "cauliflower.jpg",
        measures: {
          metric: {
            amount: 473.176,
            unitLong: "milliliters",
            unitShort: "ml",
          },
          us: {
            amount: 2.0,
            unitLong: "cups",
            unitShort: "cups",
          },
        },
        meta: ["frozen", "thawed", "cut into bite-sized pieces"],
        name: "cauliflower florets",
        original:
          "about 2 cups frozen cauliflower florets, thawed, cut into bite-sized pieces",
        originalName:
          "about frozen cauliflower florets, thawed, cut into bite-sized pieces",
        unit: "cups",
      },
      {
        aisle: "Cheese",
        amount: 2.0,
        consitency: "solid",
        id: 1041009,
        image: "cheddar-cheese.png",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
          us: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
        },
        meta: ["grated", "(I used romano)"],
        name: "cheese",
        original: "2 tbsp grated cheese (I used romano)",
        originalName: "grated cheese (I used romano)",
        unit: "tbsp",
      },
      {
        aisle: "Oil, Vinegar, Salad Dressing",
        amount: 1.0,
        consitency: "liquid",
        id: 1034053,
        image: "olive-oil.jpg",
        measures: {
          metric: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
          us: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
        },
        meta: [],
        name: "extra virgin olive oil",
        original: "1-2 tbsp extra virgin olive oil",
        originalName: "extra virgin olive oil",
        unit: "tbsp",
      },
      {
        aisle: "Produce",
        amount: 5.0,
        consitency: "solid",
        id: 11215,
        image: "garlic.jpg",
        measures: {
          metric: {
            amount: 5.0,
            unitLong: "cloves",
            unitShort: "cloves",
          },
          us: {
            amount: 5.0,
            unitLong: "cloves",
            unitShort: "cloves",
          },
        },
        meta: [],
        name: "garlic",
        original: "5-6 cloves garlic",
        originalName: "garlic",
        unit: "cloves",
      },
      {
        aisle: "Pasta and Rice",
        amount: 6.0,
        consitency: "solid",
        id: 20420,
        image: "fusilli.jpg",
        measures: {
          metric: {
            amount: 170.097,
            unitLong: "grams",
            unitShort: "g",
          },
          us: {
            amount: 6.0,
            unitLong: "ounces",
            unitShort: "oz",
          },
        },
        meta: ["(I used linguine)"],
        name: "pasta",
        original: "6-8 ounces pasta (I used linguine)",
        originalName: "pasta (I used linguine)",
        unit: "ounces",
      },
      {
        aisle: "Spices and Seasonings",
        amount: 2.0,
        consitency: "solid",
        id: 1032009,
        image: "red-pepper-flakes.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "pinches",
            unitShort: "pinches",
          },
          us: {
            amount: 2.0,
            unitLong: "pinches",
            unitShort: "pinches",
          },
        },
        meta: ["red"],
        name: "red pepper flakes",
        original: "couple of pinches red pepper flakes, optional",
        originalName: "couple of red pepper flakes, optional",
        unit: "pinches",
      },
      {
        aisle: "Spices and Seasonings",
        amount: 2.0,
        consitency: "solid",
        id: 1102047,
        image: "salt-and-pepper.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "servings",
            unitShort: "servings",
          },
          us: {
            amount: 2.0,
            unitLong: "servings",
            unitShort: "servings",
          },
        },
        meta: ["to taste"],
        name: "salt and pepper",
        original: "salt and pepper, to taste",
        originalName: "salt and pepper, to taste",
        unit: "servings",
      },
      {
        aisle: "Produce",
        amount: 3.0,
        consitency: "solid",
        id: 11291,
        image: "spring-onions.jpg",
        measures: {
          metric: {
            amount: 3.0,
            unitLong: "",
            unitShort: "",
          },
          us: {
            amount: 3.0,
            unitLong: "",
            unitShort: "",
          },
        },
        meta: ["white", "green", "separated", "chopped"],
        name: "scallions",
        original: "3 scallions, chopped, white and green parts separated",
        originalName: "scallions, chopped, white and green parts separated",
        unit: "",
      },
      {
        aisle: "Alcoholic Beverages",
        amount: 2.0,
        consitency: "liquid",
        id: 14106,
        image: "white-wine.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
          us: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
        },
        meta: ["white"],
        name: "white wine",
        original: "2-3 tbsp white wine",
        originalName: "white wine",
        unit: "tbsp",
      },
      {
        aisle: "Pasta and Rice",
        amount: 0.25,
        consitency: "solid",
        id: 99025,
        image: "breadcrumbs.jpg",
        measures: {
          metric: {
            amount: 59.147,
            unitLong: "milliliters",
            unitShort: "ml",
          },
          us: {
            amount: 0.25,
            unitLong: "cups",
            unitShort: "cups",
          },
        },
        meta: ["whole wheat", "(I used panko)"],
        name: "whole wheat bread crumbs",
        original: "1/4 cup whole wheat bread crumbs (I used panko)",
        originalName: "whole wheat bread crumbs (I used panko)",
        unit: "cup",
      },
    ],
    summary:
      'Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs might be a good recipe to expand your main course repertoire. One portion of this dish contains approximately <b>19g of protein </b>,  <b>20g of fat </b>, and a total of  <b>584 calories </b>. For  <b>$1.63 per serving </b>, this recipe  <b>covers 23% </b> of your daily requirements of vitamins and minerals. This recipe serves 2. It is brought to you by fullbellysisters.blogspot.com. 209 people were glad they tried this recipe. A mixture of scallions, salt and pepper, white wine, and a handful of other ingredients are all it takes to make this recipe so scrumptious. From preparation to the plate, this recipe takes approximately  <b>45 minutes </b>. All things considered, we decided this recipe  <b>deserves a spoonacular score of 83% </b>. This score is awesome. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/cauliflower-gratin-with-garlic-breadcrumbs-318375">Cauliflower Gratin with Garlic Breadcrumbs</a>, < href="https://spoonacular.com/recipes/pasta-with-cauliflower-sausage-breadcrumbs-30437">Pasta With Cauliflower, Sausage, & Breadcrumbs</a>, and <a href="https://spoonacular.com/recipes/pasta-with-roasted-cauliflower-parsley-and-breadcrumbs-30738">Pasta With Roasted Cauliflower, Parsley, And Breadcrumbs</a>.',
    winePairing: {
      pairedWines: ["chardonnay", "gruener veltliner", "sauvignon blanc"],
      pairingText:
        "Chardonnay, Gruener Veltliner, and Sauvignon Blanc are great choices for Pasta. Sauvignon Blanc and Gruner Veltliner both have herby notes that complement salads with enough acid to match tart vinaigrettes, while a Chardonnay can be a good pick for creamy salad dressings. The Buddha Kat Winery Chardonnay with a 4 out of 5 star rating seems like a good match. It costs about 25 dollars per bottle.",
      productMatches: [
        {
          id: 469199,
          title: "Buddha Kat Winery Chardonnay",
          description:
            "We barrel ferment our Chardonnay and age it in a mix of Oak and Stainless. Giving this light bodied wine modest oak character, a delicate floral aroma, and a warming finish.",
          price: "$25.0",
          imageUrl: "https://spoonacular.com/productImages/469199-312x231.jpg",
          averageRating: 0.8,
          ratingCount: 1.0,
          score: 0.55,
          link:
            "https://www.amazon.com/2015-Buddha-Kat-Winery-Chardonnay/dp/B00OSAVVM4?tag=spoonacular-20",
        },
      ],
    },
  };
};
export const getExampleRecipes = () => [
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 19,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 0,
    spoonacularScore: 31.0,
    healthScore: 4.0,
    creditsText: "Serious Eats",
    sourceName: "Serious Eats",
    pricePerServing: 249.04,
    extendedIngredients: [
      {
        id: 93820,
        aisle: "Cheese",
        image: "white-cream-fluffy.jpg",
        consistency: "solid",
        name: "mascarpone",
        original: "4 tablespoons mascarpone",
        originalString: "4 tablespoons mascarpone",
        originalName: "mascarpone",
        amount: 4.0,
        unit: "tablespoons",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 4.0, unitShort: "Tbsps", unitLong: "Tbsps" },
          metric: { amount: 4.0, unitShort: "Tbsps", unitLong: "Tbsps" },
        },
      },
      {
        id: 9316,
        aisle: "Produce",
        image: "strawberries.png",
        consistency: "solid",
        name: "strawberries",
        original: "1 cup strawberries, roughly chopped",
        originalString: "1 cup strawberries, roughly chopped",
        originalName: "strawberries, roughly chopped",
        amount: 1.0,
        unit: "cup",
        meta: ["roughly chopped"],
        metaInformation: ["roughly chopped"],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: { amount: 236.588, unitShort: "ml", unitLong: "milliliters" },
        },
      },
      {
        id: 93622,
        aisle: "Baking",
        image: "vanilla.jpg",
        consistency: "solid",
        name: "vanilla bean",
        original: "Seeds from 1/2 of a vanilla bean",
        originalString: "Seeds from 1/2 of a vanilla bean",
        originalName: "Seeds from a vanilla bean",
        amount: 0.5,
        unit: "",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 0.5, unitShort: "", unitLong: "" },
          metric: { amount: 0.5, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 19095,
        aisle: "Frozen",
        image: "vanilla-ice-cream.png",
        consistency: "solid",
        name: "vanilla ice cream",
        original: "2 cups vanilla ice cream",
        originalString: "2 cups vanilla ice cream",
        originalName: "vanilla ice cream",
        amount: 2.0,
        unit: "cups",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 2.0, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 473.176, unitShort: "ml", unitLong: "milliliters" },
        },
      },
    ],
    id: 149351,
    title: "Strawberry Mascarpone Shake",
    readyInMinutes: 5,
    servings: 2,
    sourceUrl:
      "http://www.seriouseats.com/recipes/2013/08/strawberry-shake-mascarpone-vanilla-milkshake-recipe.html",
    image: "https://spoonacular.com/recipeImages/149351-312x231.jpg",
    imageType: "jpg",
    summary:
      'Strawberry Mascarpone Shake is a <b>gluten free</b> beverage. This recipe serves 2 and costs $2.49 per serving. One portion of this dish contains approximately <b>7g of protein</b>, <b>28g of fat</b>, and a total of <b>434 calories</b>. <b>Mother\'s Day</b> will be even more special with this recipe. Not a lot of people made this recipe, and 1 would say it hit the spot. Head to the store and pick up mascarpone, strawberries, vanillan ice cream, and a few other things to make it today. From preparation to the plate, this recipe takes around <b>5 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 35%</b>. This score is rather bad. Try <a href="https://spoonacular.com/recipes/strawberry-milkshake-strawberry-short-shake-551702">Strawberry Milkshake - Strawberry Short-Shake</a>, <a href="https://spoonacular.com/recipes/strawberry-crepes-with-strawberry-mascarpone-cream-628971">Strawberry Crepes with Strawberry Mascarpone Cream</a>, and <a href="https://spoonacular.com/recipes/strawberry-shake-58234">Strawberry Shake</a> for similar recipes.',
    cuisines: [],
    dishTypes: ["side dish"],
    diets: ["gluten free"],
    occasions: ["mother's day"],
    winePairing: {},
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step:
              "Pulse the strawberries a few times in a blender then blend on medium high speed until smooth, about 30 seconds.",
            ingredients: [
              {
                id: 9316,
                name: "strawberries",
                localizedName: "strawberries",
                image: "strawberries.png",
              },
            ],
            equipment: [
              {
                id: 404726,
                name: "blender",
                localizedName: "blender",
                image: "blender.png",
              },
            ],
          },
          {
            number: 2,
            step:
              "Add the ice cream, mascarpone, and vanilla bean seeds to the strawberry puree and blend on medium high speed just until smooth, about 30 seconds.",
            ingredients: [
              {
                id: 1009316,
                name: "strawberry puree",
                localizedName: "strawberry puree",
                image: "strawberry-sauce.png",
              },
              {
                id: 93622,
                name: "vanilla bean",
                localizedName: "vanilla bean",
                image: "vanilla.jpg",
              },
              {
                id: 93820,
                name: "mascarpone",
                localizedName: "mascarpone",
                image: "white-cream-fluffy.jpg",
              },
              {
                id: 19095,
                name: "ice cream",
                localizedName: "ice cream",
                image: "vanilla-ice-cream.png",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Garnish with strawberries if desired and serve immediately.",
            ingredients: [
              {
                id: 9316,
                name: "strawberries",
                localizedName: "strawberries",
                image: "strawberries.png",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    usedIngredientCount: 2,
    missedIngredientCount: 2,
    likes: 0,
    missedIngredients: [
      {
        id: 93622,
        amount: 0.5,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Baking",
        name: "vanilla bean",
        original: "Seeds from 1/2 of a vanilla bean",
        originalString: "Seeds from 1/2 of a vanilla bean",
        originalName: "Seeds from a vanilla bean",
        metaInformation: [],
        meta: [],
        extendedName: "vanilla bean bean",
        image: "https://spoonacular.com/cdn/ingredients_100x100/vanilla.jpg",
      },
      {
        id: 19095,
        amount: 2.0,
        unit: "cups",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Frozen",
        name: "vanilla ice cream",
        original: "2 cups vanilla ice cream",
        originalString: "2 cups vanilla ice cream",
        originalName: "vanilla ice cream",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/vanilla-ice-cream.png",
      },
    ],
    usedIngredients: [
      {
        id: 93820,
        amount: 4.0,
        unit: "tablespoons",
        unitLong: "tablespoons",
        unitShort: "Tbsp",
        aisle: "Cheese",
        name: "mascarpone",
        original: "4 tablespoons mascarpone",
        originalString: "4 tablespoons mascarpone",
        originalName: "mascarpone",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
      {
        id: 9316,
        amount: 1.0,
        unit: "cup",
        unitLong: "cup",
        unitShort: "cup",
        aisle: "Produce",
        name: "strawberries",
        original: "1 cup strawberries, roughly chopped",
        originalString: "1 cup strawberries, roughly chopped",
        originalName: "strawberries, roughly chopped",
        metaInformation: ["roughly chopped"],
        meta: ["roughly chopped"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/strawberries.png",
      },
    ],
    unusedIngredients: [],
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 26,
    gaps: "no",
    lowFodmap: false,
    preparationMinutes: 30,
    cookingMinutes: 0,
    aggregateLikes: 91,
    spoonacularScore: 28.0,
    healthScore: 2.0,
    creditsText: "BBC Good Food",
    sourceName: "BBC Good Food",
    pricePerServing: 175.67,
    extendedIngredients: [
      {
        id: 98843,
        aisle: "Sweet Snacks",
        image: "biscotti.jpg",
        consistency: "solid",
        name: "biscotti",
        original: "250g box biscotti biscuits",
        originalString: "250g box biscotti biscuits",
        originalName: "box biscotti biscuits",
        amount: 250.0,
        unit: "g",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 8.818, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 250.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 9316,
        aisle: "Produce",
        image: "strawberries.png",
        consistency: "solid",
        name: "strawberries",
        original: "400g punnet strawberries, hulled and halved",
        originalString: "400g punnet strawberries, hulled and halved",
        originalName: "punnet strawberries, hulled and halved",
        amount: 400.0,
        unit: "g",
        meta: ["hulled", "halved"],
        metaInformation: ["hulled", "halved"],
        measures: {
          us: { amount: 14.11, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 400.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 19334,
        aisle: "Baking",
        image: "light-brown-sugar.jpg",
        consistency: "solid",
        name: "golden brown sugar",
        original: "50g golden caster sugar",
        originalString: "50g golden caster sugar",
        originalName: "golden caster sugar",
        amount: 50.0,
        unit: "g",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.764, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 50.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 93820,
        aisle: "Cheese",
        image: "white-cream-fluffy.jpg",
        consistency: "solid",
        name: "mascarpone",
        original: "250g tub mascarpone",
        originalString: "250g tub mascarpone",
        originalName: "mascarpone",
        amount: 250.0,
        unit: "g",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 8.818, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 250.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 1011053,
        aisle: "Milk, Eggs, Other Dairy",
        image: "white-cream.png",
        consistency: "liquid",
        name: "double cream",
        original: "284ml carton double cream, softly whipped",
        originalString: "284ml carton double cream, softly whipped",
        originalName: "carton double cream, softly whipped",
        amount: 284.0,
        unit: "ml",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.2, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 284.0, unitShort: "ml", unitLong: "milliliters" },
        },
      },
      {
        id: null,
        aisle: "?",
        image: null,
        consistency: null,
        name: "vin santo",
        original: "100ml Vin Santo or other sweet dessert wine",
        originalString: "100ml Vin Santo or other sweet dessert wine",
        originalName: "Vin Santo or other sweet dessert wine",
        amount: 100.0,
        unit: "ml",
        meta: ["sweet"],
        metaInformation: ["sweet"],
        measures: {
          us: { amount: 3.382, unitShort: "fl. oz", unitLong: "fl. ozs" },
          metric: { amount: 100.0, unitShort: "ml", unitLong: "milliliters" },
        },
      },
    ],
    id: 224626,
    title: "Strawberry parfait with Vin Santo, mascarpone & biscotti",
    readyInMinutes: 30,
    servings: 6,
    sourceUrl:
      "https://www.bbcgoodfood.com/recipes/2165/strawberry-parfait-with-vin-santo-mascarpone-and-b",
    image: "https://spoonacular.com/recipeImages/224626-312x231.jpg",
    imageType: "jpg",
    summary:
      'The recipe Strawberry parfait with Vin Santo, mascarpone & biscotti could satisfy your Mediterranean craving in about <b>30 minutes</b>. This recipe makes 6 servings with <b>596 calories</b>, <b>9g of protein</b>, and <b>43g of fat</b> each. For <b>$1.76 per serving</b>, this recipe <b>covers 7%</b> of your daily requirements of vitamins and minerals. It is brought to you by BBC Good Food. <b>Mother\'s Day</b> will be even more special with this recipe. If you have carton double cream, vin santo, golden caster sugar, and a few other ingredients on hand, you can make it. A couple people made this recipe, and 91 would say it hit the spot. Overall, this recipe earns a <b>rather bad spoonacular score of 27%</b>. Similar recipes include <a href="https://spoonacular.com/recipes/biscotti-vin-santo-598516">Biscotti & Vin Santo</a>, <a href="https://spoonacular.com/recipes/panna-cotta-with-strawberry-vin-santo-sauce-154216">Panna Cotta with Strawberry-Vin Santo Sauce</a>, and <a href="https://spoonacular.com/recipes/asparagus-with-vin-santo-vinaigrette-330874">Asparagus with Vin Santo Vinaigrette</a>.',
    cuisines: ["Mediterranean", "Italian", "European"],
    dishTypes: [],
    diets: [],
    occasions: ["mother's day"],
    winePairing: {
      pairedWines: ["cream sherry", "moscato dasti", "port"],
      pairingText:
        "Parfait works really well with Cream Sherry, Moscato d'Asti, and Port. A common wine pairing rule is to make sure your wine is sweeter than your food. Delicate desserts go well with Moscato d'Asti, nutty desserts with cream sherry, and caramel or chocolate desserts pair well with port. You could try NV Solera Cream Sherry. Reviewers quite like it with a 4.5 out of 5 star rating and a price of about 17 dollars per bottle.",
      productMatches: [
        {
          id: 428475,
          title: "NV Solera Cream Sherry",
          description:
            "The Solera Cream Sherry has a brilliant amber and deep copper hue. With butterscotch and pecan aromas, the sweet salted nut and brown spice aromas carry a complex caramel accent. A sweet entry leads to a rounded, lush, moderately full-bodied palate with a lengthy, flavorful finish.",
          price: "$16.99",
          imageUrl: "https://spoonacular.com/productImages/428475-312x231.jpg",
          averageRating: 0.9,
          ratingCount: 4.0,
          score: 0.823076923076923,
          link:
            "https://www.amazon.com/NV-Solera-Cream-Sherry-750/dp/B00HSME8OW?tag=spoonacular-20",
        },
      ],
    },
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step:
              "Place the biscotti biscuits in a plastic bag and crush them lightly with the end of a rolling pin, leaving them slightly chunky. Tip the crushed biscuits into a bowl, drizzle over the Vin Santo and give it a stir. In small bowl, use a fork to slightly mash half of the strawberries with the sugar.",
            ingredients: [
              {
                id: 9316,
                name: "strawberries",
                localizedName: "strawberries",
                image: "strawberries.png",
              },
              {
                id: 98843,
                name: "biscotti",
                localizedName: "biscotti",
                image: "biscotti.jpg",
              },
            ],
            equipment: [
              {
                id: 221671,
                name: "ziploc bags",
                localizedName: "ziploc bags",
                image: "plastic-bag.jpg",
              },
              {
                id: 404746,
                name: "rolling pin",
                localizedName: "rolling pin",
                image: "rolling-pin.jpg",
              },
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
            ],
          },
          {
            number: 2,
            step:
              "Whip the mascarpone in a medium bowl, then fold into the whipped cream. If the mixture appears too thick fold through a little milk. In a 1-litre glass bowl, spread half of the soaked biscotti. Top with half of the mashed strawberries and then half of the mascarpone mixture. Repeat until you have used up everything. Slice the remaining strawberries and scatter over the top. Refrigerate, then pack into a cooler as this dessert should be served chilled.",
            ingredients: [
              {
                id: 9316,
                name: "strawberries",
                localizedName: "strawberries",
                image: "strawberries.png",
              },
              {
                id: 93820,
                name: "mascarpone",
                localizedName: "mascarpone",
                image: "white-cream-fluffy.jpg",
              },
              {
                id: 98843,
                name: "biscotti",
                localizedName: "biscotti",
                image: "biscotti.jpg",
              },
            ],
            equipment: [
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
            ],
          },
        ],
      },
    ],
    usedIngredientCount: 2,
    missedIngredientCount: 2,
    likes: 0,
    missedIngredients: [
      {
        id: 98843,
        amount: 250.0,
        unit: "g",
        unitLong: "grams",
        unitShort: "g",
        aisle: "Sweet Snacks",
        name: "biscotti",
        original: "250g box biscotti biscuits",
        originalString: "250g box biscotti biscuits",
        originalName: "box biscotti biscuits",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/biscotti.jpg",
      },
      {
        id: 1011053,
        amount: 284.0,
        unit: "ml",
        unitLong: "milliliters",
        unitShort: "ml",
        aisle: "Milk, Eggs, Other Dairy",
        name: "double cream",
        original: "284ml carton double cream, softly whipped",
        originalString: "284ml carton double cream, softly whipped",
        originalName: "carton double cream, softly whipped",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream.png",
      },
    ],
    usedIngredients: [
      {
        id: 9316,
        amount: 400.0,
        unit: "g",
        unitLong: "grams",
        unitShort: "g",
        aisle: "Produce",
        name: "strawberries",
        original: "400g punnet strawberries, hulled and halved",
        originalString: "400g punnet strawberries, hulled and halved",
        originalName: "punnet strawberries, hulled and halved",
        metaInformation: ["hulled", "halved"],
        meta: ["hulled", "halved"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/strawberries.png",
      },
      {
        id: 93820,
        amount: 250.0,
        unit: "g",
        unitLong: "grams",
        unitShort: "g",
        aisle: "Cheese",
        name: "mascarpone",
        original: "250g tub mascarpone",
        originalString: "250g tub mascarpone",
        originalName: "mascarpone",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
    ],
    unusedIngredients: [],
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 2,
    gaps: "no",
    lowFodmap: false,
    preparationMinutes: 30,
    cookingMinutes: 360,
    aggregateLikes: 71,
    spoonacularScore: 8.0,
    healthScore: 0.0,
    creditsText: "BBC Good Food",
    sourceName: "BBC Good Food",
    pricePerServing: 50.77,
    extendedIngredients: [
      {
        id: 9316,
        aisle: "Produce",
        image: "strawberries.png",
        consistency: "solid",
        name: "strawberries",
        original: "1 x 400g punnet strawberries",
        originalString: "1 x 400g punnet strawberries",
        originalName: "x 400g punnet strawberries",
        amount: 1.0,
        unit: "",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.0, unitShort: "", unitLong: "" },
          metric: { amount: 1.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 93820,
        aisle: "Cheese",
        image: "white-cream-fluffy.jpg",
        consistency: "solid",
        name: "mascarpone",
        original: "1 x 250g tub mascarpone",
        originalString: "1 x 250g tub mascarpone",
        originalName: "x 250g tub mascarpone",
        amount: 1.0,
        unit: "",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.0, unitShort: "", unitLong: "" },
          metric: { amount: 1.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 1095,
        aisle: "Baking",
        image: "evaporated-milk.png",
        consistency: "solid",
        name: "condensed milk",
        original: "½ x 397g can condensed milk",
        originalString: "½ x 397g can condensed milk",
        originalName: "x 397g can condensed milk",
        amount: 0.5,
        unit: "",
        meta: ["canned"],
        metaInformation: ["canned"],
        measures: {
          us: { amount: 0.5, unitShort: "", unitLong: "" },
          metric: { amount: 0.5, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 93645,
        aisle: "Baking",
        image: "nonpareils.jpg",
        consistency: "solid",
        name: "sprinkles",
        original: "cones and sprinkles, to serve",
        originalString: "cones and sprinkles, to serve",
        originalName: "cones and sprinkles, to serve",
        amount: 1.0,
        unit: "serving",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.0, unitShort: "serving", unitLong: "serving" },
          metric: { amount: 1.0, unitShort: "serving", unitLong: "serving" },
        },
      },
    ],
    id: 211582,
    title: "Easy strawberry ice cream",
    readyInMinutes: 390,
    servings: 1,
    sourceUrl:
      "https://www.bbcgoodfood.com/recipes/531636/easy-strawberry-ice-cream",
    image: "https://spoonacular.com/recipeImages/211582-312x231.jpg",
    imageType: "jpg",
    summary:
      'Easy strawberry ice cream requires around <b>6 hours and 30 minutes</b> from start to finish. This recipe makes 1 servings with <b>52 calories</b>, <b>0g of protein</b>, and <b>1g of fat</b> each. For <b>51 cents per serving</b>, this recipe <b>covers 1%</b> of your daily requirements of vitamins and minerals. 71 person were glad they tried this recipe. A mixture of g punnet strawberries, g tub mascarpone, cones and sprinkles, and a handful of other ingredients are all it takes to make this recipe so delicious. It can be enjoyed any time, but it is especially good for <b>Mother\'s Day</b>. It is brought to you by BBC Good Food. It is a good option if you\'re following a <b>gluten free</b> diet. Overall, this recipe earns a <b>very bad (but still fixable) spoonacular score of 6%</b>. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/easy-eggless-strawberry-ice-cream-625086">Easy, Eggless Strawberry Ice Cream</a>, <a href="https://spoonacular.com/recipes/roasted-strawberry-coconut-milk-ice-cream-vegan-+-tips-for-making-your-homemade-ice-cream-soft-814136">Roasted Strawberry Coconut Milk Ice Cream (Vegan) + Tips for Making Your Homemade Ice Cream Soft</a>, and <a href="https://spoonacular.com/recipes/easy-chocolate-vanilla-ice-cream-cake-with-ice-cream-sandwiches-608339">Easy Chocolate Vanillan Ice Cream Cake (with ice cream sandwiches)</a>.',
    cuisines: [],
    dishTypes: [],
    diets: ["gluten free"],
    occasions: ["mother's day", "summer"],
    winePairing: {
      pairedWines: ["cream sherry", "moscato dasti", "port"],
      pairingText:
        "Cream Sherry, Moscato d'Asti, and Port are my top picks for Strawberry Ice Cream. A common wine pairing rule is to make sure your wine is sweeter than your food. Delicate desserts go well with Moscato d'Asti, nutty desserts with cream sherry, and caramel or chocolate desserts pair well with port. One wine you could try is NV Johnson Estate Cream Sherry. It has 5 out of 5 stars and a bottle costs about 19 dollars.",
      productMatches: [
        {
          id: 430626,
          title: "NV Johnson Estate Cream Sherry",
          description:
            'Very aromatic with notes of hazelnut, vanilla, and a touch of oak followed by sweet raisins and a touch of yeast. Clean lasting finish. Good now but will reward those allow it to age"". A favorite pre-prandial beverage. Consider it with nuts before dinner as an aperitif, or after dinner with dessert, especially chocolates and fruit-based desserts. Also wonderful on cold afternoons, served with biscotti to dip in ""Italian-style"". "',
          price: "$19.49",
          imageUrl: "https://spoonacular.com/productImages/430626-312x231.jpg",
          averageRating: 1.0,
          ratingCount: 2.0,
          score: 0.8571428571428572,
          link:
            "https://www.amazon.com/Johnson-Estate-Cream-Sherry-750/dp/B00D3GQSRW?tag=spoonacular-20",
        },
      ],
    },
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step:
              "Pull the green hulls out of the strawberries. If they are still quite hard, cut them in half or quarters with a table knife. Tip them into a flat-bottomed dish.",
            ingredients: [
              {
                id: 9316,
                name: "strawberries",
                localizedName: "strawberries",
                image: "strawberries.png",
              },
            ],
            equipment: [
              {
                id: 404745,
                name: "knife",
                localizedName: "knife",
                image: "chefs-knife.jpg",
              },
            ],
          },
          {
            number: 2,
            step:
              "Use a potato masher to squash the strawberries as much as you can. Tip into a bowl. Ask your grown-up helper to give you a hand if you need to.",
            ingredients: [
              {
                id: 9316,
                name: "strawberries",
                localizedName: "strawberries",
                image: "strawberries.png",
              },
            ],
            equipment: [
              {
                id: 404763,
                name: "potato masher",
                localizedName: "potato masher",
                image: "potato-masher.jpg",
              },
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
            ],
          },
          {
            number: 3,
            step:
              "Add the mascarpone and mash this in  dont worry if it is a bit lumpy.",
            ingredients: [
              {
                id: 93820,
                name: "mascarpone",
                localizedName: "mascarpone",
                image: "white-cream-fluffy.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 4,
            step:
              "Add the condensed milk and mix everything together. Dont worry if the mix is streaky.",
            ingredients: [
              {
                id: 1095,
                name: "sweetened condensed milk",
                localizedName: "sweetened condensed milk",
                image: "evaporated-milk.png",
              },
            ],
            equipment: [],
          },
          {
            number: 5,
            step:
              "Spoon the mixture into a metal or plastic box and put it in the freezer. Wait until the next day or at least 6 hours before scooping into bowls or cones. Decorate how you like.",
            ingredients: [],
            equipment: [
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
            ],
          },
        ],
      },
    ],
    usedIngredientCount: 2,
    missedIngredientCount: 2,
    likes: 0,
    missedIngredients: [
      {
        id: 1095,
        amount: 0.5,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Baking",
        name: "condensed milk",
        original: "½ x 397g can condensed milk",
        originalString: "½ x 397g can condensed milk",
        originalName: "x 397g can condensed milk",
        metaInformation: ["canned"],
        meta: ["canned"],
        extendedName: "canned condensed milk",
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/evaporated-milk.png",
      },
      {
        id: 93645,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Baking",
        name: "sprinkles",
        original: "cones and sprinkles, to serve",
        originalString: "cones and sprinkles, to serve",
        originalName: "cones and sprinkles, to serve",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/nonpareils.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 9316,
        amount: 1.0,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Produce",
        name: "strawberries",
        original: "1 x 400g punnet strawberries",
        originalString: "1 x 400g punnet strawberries",
        originalName: "x 400g punnet strawberries",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/strawberries.png",
      },
      {
        id: 93820,
        amount: 1.0,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Cheese",
        name: "mascarpone",
        original: "1 x 250g tub mascarpone",
        originalString: "1 x 250g tub mascarpone",
        originalName: "x 250g tub mascarpone",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
    ],
    unusedIngredients: [],
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: true,
    sustainable: false,
    weightWatcherSmartPoints: 24,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 702,
    spoonacularScore: 65.0,
    healthScore: 10.0,
    creditsText: "In Simones Kitchen",
    sourceName: "In Simones Kitchen",
    pricePerServing: 236.96,
    extendedIngredients: [
      {
        id: 18423,
        aisle: "Sweet Snacks",
        image: "ladyfingers.png",
        consistency: "solid",
        name: "lady fingers",
        original:
          "1-2 packages of lady fingers (depending on the size of your bowl)",
        originalString:
          "1-2 packages of lady fingers (depending on the size of your bowl)",
        originalName: "lady fingers (depending on the size of your bowl)",
        amount: 1.0,
        unit: "packages",
        meta: ["(depending on the size of your bowl)"],
        metaInformation: ["(depending on the size of your bowl)"],
        measures: {
          us: { amount: 1.0, unitShort: "pkg", unitLong: "package" },
          metric: { amount: 1.0, unitShort: "pkg", unitLong: "package" },
        },
      },
      {
        id: 93820,
        aisle: "Cheese",
        image: "white-cream-fluffy.jpg",
        consistency: "solid",
        name: "mascarpone",
        original: "250 gr mascarpone",
        originalString: "250 gr mascarpone",
        originalName: "mascarpone",
        amount: 250.0,
        unit: "gr",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 8.818, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 250.0, unitShort: "gr", unitLong: "grs" },
        },
      },
      {
        id: 9206,
        aisle: "Beverages",
        image: "orange-juice.jpg",
        consistency: "liquid",
        name: "orange juice",
        original: "Orange juice, freshly squeezed",
        originalString: "Orange juice, freshly squeezed",
        originalName: "Orange juice, freshly squeezed",
        amount: 6.0,
        unit: "servings",
        meta: ["freshly squeezed"],
        metaInformation: ["freshly squeezed"],
        measures: {
          us: { amount: 6.0, unitShort: "servings", unitLong: "servings" },
          metric: { amount: 6.0, unitShort: "servings", unitLong: "servings" },
        },
      },
      {
        id: 9316,
        aisle: "Produce",
        image: "strawberries.png",
        consistency: "solid",
        name: "strawberries",
        original: "fresh strawberries",
        originalString: "fresh strawberries",
        originalName: "fresh strawberries",
        amount: 6.0,
        unit: "servings",
        meta: ["fresh"],
        metaInformation: ["fresh"],
        measures: {
          us: { amount: 6.0, unitShort: "servings", unitLong: "servings" },
          metric: { amount: 6.0, unitShort: "servings", unitLong: "servings" },
        },
      },
      {
        id: 19335,
        aisle: "Baking",
        image: "sugar-in-bowl.png",
        consistency: "solid",
        name: "sugar",
        original: "40 gr sugar",
        originalString: "40 gr sugar",
        originalName: "sugar",
        amount: 40.0,
        unit: "gr",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.411, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 40.0, unitShort: "gr", unitLong: "grs" },
        },
      },
      {
        id: 1001053,
        aisle: "Milk, Eggs, Other Dairy",
        image: "fluid-cream.jpg",
        consistency: "liquid",
        name: "whipping cream",
        original: "250 ml whipping cream",
        originalString: "250 ml whipping cream",
        originalName: "whipping cream",
        amount: 250.0,
        unit: "ml",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.057, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 250.0, unitShort: "ml", unitLong: "milliliters" },
        },
      },
      {
        id: null,
        aisle: "?",
        image: null,
        consistency: null,
        name: "cacaopowder if you like",
        original: "cacaopowder if you like for decorating",
        originalString: "cacaopowder if you like for decorating",
        originalName: "cacaopowder if you like for decorating",
        amount: 6.0,
        unit: "servings",
        meta: ["for decorating"],
        metaInformation: ["for decorating"],
        measures: {
          us: { amount: 6.0, unitShort: "servings", unitLong: "servings" },
          metric: { amount: 6.0, unitShort: "servings", unitLong: "servings" },
        },
      },
      {
        id: null,
        aisle: "?",
        image: null,
        consistency: null,
        name: "make your own",
        original: "1 bottle of strawberry sauce or make your own",
        originalString: "1 bottle of strawberry sauce or make your own",
        originalName: "strawberry sauce or make your own",
        amount: 1.0,
        unit: "bottle",
        meta: [],
        metaInformation: [],
        measures: {
          us: { amount: 1.0, unitShort: "bottle", unitLong: "bottle" },
          metric: { amount: 1.0, unitShort: "bottle", unitLong: "bottle" },
        },
      },
    ],
    id: 588984,
    title: "Strawberry tiramisu | Simone's KitchenSimone's Kitchen",
    readyInMinutes: 45,
    servings: 6,
    sourceUrl: "http://insimoneskitchen.com/strawberry-tiramisu/",
    image: "https://spoonacular.com/recipeImages/588984-312x231.jpg",
    imageType: "jpg",
    summary:
      "The recipe Strawberry tiramisu | Simone's KitchenSimone's Kitchen could satisfy your Mediterranean craving in approximately <b>45 minutes</b>. This recipe makes 6 servings with <b>600 calories</b>, <b>9g of protein</b>, and <b>38g of fat</b> each. For <b>$2.37 per serving</b>, this recipe <b>covers 16%</b> of your daily requirements of vitamins and minerals. <b>Mother's Day</b> will be even more special with this recipe. This recipe from In Simones Kitchen has 702 fans. Head to the store and pick up whipping cream, orange juice, sugar, and a few other things to make it today. All things considered, we decided this recipe <b>deserves a spoonacular score of 68%</b>. This score is pretty good. Try <a href=\"https://spoonacular.com/recipes/strawberry-watermelon-popsicles-simones-kitchensimones-kitchen-588983\">Strawberry watermelon popsicles | Simone's KitchenSimone's Kitchen</a>, <a href=\"https://spoonacular.com/recipes/strawberry-salad-with-halloumi-simones-kitchensimones-kitchen-589025\">Strawberry salad with halloumi | Simone's KitchenSimone's Kitchen</a>, and <a href=\"https://spoonacular.com/recipes/whole30-day-1-strawberry-salad-with-raspberry-dressing-simones-kitchensimones-kitchen-589080\">Whole30 day #1; strawberry salad with raspberry dressing | Simone's KitchenSimone's Kitchen</a> for similar recipes.",
    cuisines: ["Mediterranean", "Italian", "European"],
    dishTypes: ["side dish"],
    diets: [],
    occasions: ["mother's day"],
    winePairing: {
      pairedWines: ["chianti", "trebbiano", "verdicchio"],
      pairingText:
        "Chianti, Trebbiano, and Verdicchio are great choices for Italian. Italians know food and they know wine. Trebbiano and Verdicchio are Italian white wines that pair well with fish and white meat, while Chianti is a great Italian red for heavier, bolder dishes. You could try Rodano Vigna Viacosta Chianti Classico. Reviewers quite like it with a 4.3 out of 5 star rating and a price of about 30 dollars per bottle.",
      productMatches: [
        {
          id: 459637,
          title: "Rodano Vigna Viacosta Chianti Classico",
          description:
            "Deep concentration of Sangiovese flavors of classic cherry, earth and a hint of smoky pistachio nuts. Made with 100% Sangiovese.",
          price: "$29.99",
          imageUrl: "https://spoonacular.com/productImages/459637-312x231.jpg",
          averageRating: 0.86,
          ratingCount: 6.0,
          score: 0.8073684210526315,
          link:
            "https://click.linksynergy.com/deeplink?id=*QCiIS6t4gA&mid=2025&murl=https%3A%2F%2Fwww.wine.com%2Fproduct%2Frodano-vigna-viacosta-chianti-classico-2010%2F164552",
        },
      ],
    },
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step:
              "Whip the cream together with the sugar till you have soft peaks.",
            ingredients: [
              {
                id: 1053,
                name: "cream",
                localizedName: "cream",
                image: "fluid-cream.jpg",
              },
              {
                id: 19335,
                name: "sugar",
                localizedName: "sugar",
                image: "sugar-in-bowl.png",
              },
            ],
            equipment: [],
          },
          {
            number: 2,
            step:
              "Mix the cream together with the mascarpone until you have a smooth mixture.",
            ingredients: [
              {
                id: 93820,
                name: "mascarpone",
                localizedName: "mascarpone",
                image: "white-cream-fluffy.jpg",
              },
              {
                id: 1053,
                name: "cream",
                localizedName: "cream",
                image: "fluid-cream.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step:
              "Mix a little of the orange juice with the strawberry sauce (you can always make more if you want) and dip the ladyfingers in the mixture. Don’t leave them in too long or they will get soggy but also don’t leave them in too short or the ladyfingers will not be moist enough.Make a layer of the ladyfingers in the bottom of a pretty bowl and add a layer of the mascarpone/cream mixture, put a layer of fresh strawberry slices on top. Repeat until you are out of supplies or until you have reached the edge of the bowl. Make sure you leave enough strawberries for one final layer on top later!Leave to stand in the fridge for at least 2-4 hours before putting on the last layer of strawberries and serve immediately. If you like you can sprinkle some cacaopowder on top too.",
            ingredients: [
              {
                id: 9206,
                name: "orange juice",
                localizedName: "orange juice",
                image: "orange-juice.jpg",
              },
              {
                id: 9316,
                name: "strawberries",
                localizedName: "strawberries",
                image: "strawberries.png",
              },
              {
                id: 18423,
                name: "ladyfingers",
                localizedName: "ladyfingers",
                image: "ladyfingers.png",
              },
              {
                id: 93820,
                name: "mascarpone",
                localizedName: "mascarpone",
                image: "white-cream-fluffy.jpg",
              },
              {
                id: 1053,
                name: "cream",
                localizedName: "cream",
                image: "fluid-cream.jpg",
              },
            ],
            equipment: [
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
            ],
          },
        ],
      },
    ],
    usedIngredientCount: 2,
    missedIngredientCount: 3,
    likes: 0,
    missedIngredients: [
      {
        id: 18423,
        amount: 1.0,
        unit: "packages",
        unitLong: "package",
        unitShort: "pkg",
        aisle: "Sweet Snacks",
        name: "lady fingers",
        original:
          "1-2 packages of lady fingers (depending on the size of your bowl)",
        originalString:
          "1-2 packages of lady fingers (depending on the size of your bowl)",
        originalName: "lady fingers (depending on the size of your bowl)",
        metaInformation: ["(depending on the size of your bowl)"],
        meta: ["(depending on the size of your bowl)"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/ladyfingers.png",
      },
      {
        id: 9206,
        amount: 6.0,
        unit: "servings",
        unitLong: "servings",
        unitShort: "servings",
        aisle: "Beverages",
        name: "orange juice",
        original: "Orange juice, freshly squeezed",
        originalString: "Orange juice, freshly squeezed",
        originalName: "Orange juice, freshly squeezed",
        metaInformation: ["freshly squeezed"],
        meta: ["freshly squeezed"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/orange-juice.jpg",
      },
      {
        id: 1001053,
        amount: 250.0,
        unit: "ml",
        unitLong: "milliliters",
        unitShort: "ml",
        aisle: "Milk, Eggs, Other Dairy",
        name: "whipping cream",
        original: "250 ml whipping cream",
        originalString: "250 ml whipping cream",
        originalName: "whipping cream",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/fluid-cream.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 93820,
        amount: 250.0,
        unit: "gr",
        unitLong: "grs",
        unitShort: "gr",
        aisle: "Cheese",
        name: "mascarpone",
        original: "250 gr mascarpone",
        originalString: "250 gr mascarpone",
        originalName: "mascarpone",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
      {
        id: 9316,
        amount: 6.0,
        unit: "servings",
        unitLong: "servings",
        unitShort: "servings",
        aisle: "Produce",
        name: "strawberries",
        original: "fresh strawberries",
        originalString: "fresh strawberries",
        originalName: "fresh strawberries",
        metaInformation: ["fresh"],
        meta: ["fresh"],
        extendedName: "fresh strawberries",
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/strawberries.png",
      },
    ],
    unusedIngredients: [],
  },
];
