export const getExampleRecipeInfo = () => {
  return {
    id: 716429,
    title: "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs",
    image: "https://spoonacular.com/recipeImages/716429-556x370.jpg",
    imageType: "jpg",
    servings: 2,
    readyInMinutes: 45,
    license: "CC BY-SA 3.0",
    sourceName: "Full Belly Sisters",
    sourceUrl:
      "http://fullbellysisters.blogspot.com/2012/06/pasta-with-garlic-scallions-cauliflower.html",
    spoonacularSourceUrl:
      "https://spoonacular.com/pasta-with-garlic-scallions-cauliflower-breadcrumbs-716429",
    aggregateLikes: 209,
    healthScore: 19.0,
    spoonacularScore: 83.0,
    pricePerServing: 163.15,
    analyzedInstructions: [],
    cheap: false,
    creditsText: "Full Belly Sisters",
    cuisines: [],
    dairyFree: false,
    diets: [],
    gaps: "no",
    glutenFree: false,
    instructions: "",
    ketogenic: false,
    lowFodmap: false,
    occasions: [],
    sustainable: false,
    vegan: false,
    vegetarian: false,
    veryHealthy: false,
    veryPopular: false,
    whole30: false,
    weightWatcherSmartPoints: 17,
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    extendedIngredients: [
      {
        aisle: "Milk, Eggs, Other Dairy",
        amount: 1.0,
        consitency: "solid",
        id: 1001,
        image: "butter-sliced.jpg",
        measures: {
          metric: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
          us: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
        },
        meta: [],
        name: "butter",
        original: "1 tbsp butter",
        originalName: "butter",
        unit: "tbsp",
      },
      {
        aisle: "Produce",
        amount: 2.0,
        consitency: "solid",
        id: 10011135,
        image: "cauliflower.jpg",
        measures: {
          metric: {
            amount: 473.176,
            unitLong: "milliliters",
            unitShort: "ml",
          },
          us: {
            amount: 2.0,
            unitLong: "cups",
            unitShort: "cups",
          },
        },
        meta: ["frozen", "thawed", "cut into bite-sized pieces"],
        name: "cauliflower florets",
        original:
          "about 2 cups frozen cauliflower florets, thawed, cut into bite-sized pieces",
        originalName:
          "about frozen cauliflower florets, thawed, cut into bite-sized pieces",
        unit: "cups",
      },
      {
        aisle: "Cheese",
        amount: 2.0,
        consitency: "solid",
        id: 1041009,
        image: "cheddar-cheese.png",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
          us: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
        },
        meta: ["grated", "(I used romano)"],
        name: "cheese",
        original: "2 tbsp grated cheese (I used romano)",
        originalName: "grated cheese (I used romano)",
        unit: "tbsp",
      },
      {
        aisle: "Oil, Vinegar, Salad Dressing",
        amount: 1.0,
        consitency: "liquid",
        id: 1034053,
        image: "olive-oil.jpg",
        measures: {
          metric: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
          us: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
        },
        meta: [],
        name: "extra virgin olive oil",
        original: "1-2 tbsp extra virgin olive oil",
        originalName: "extra virgin olive oil",
        unit: "tbsp",
      },
      {
        aisle: "Produce",
        amount: 5.0,
        consitency: "solid",
        id: 11215,
        image: "garlic.jpg",
        measures: {
          metric: {
            amount: 5.0,
            unitLong: "cloves",
            unitShort: "cloves",
          },
          us: {
            amount: 5.0,
            unitLong: "cloves",
            unitShort: "cloves",
          },
        },
        meta: [],
        name: "garlic",
        original: "5-6 cloves garlic",
        originalName: "garlic",
        unit: "cloves",
      },
      {
        aisle: "Pasta and Rice",
        amount: 6.0,
        consitency: "solid",
        id: 20420,
        image: "fusilli.jpg",
        measures: {
          metric: {
            amount: 170.097,
            unitLong: "grams",
            unitShort: "g",
          },
          us: {
            amount: 6.0,
            unitLong: "ounces",
            unitShort: "oz",
          },
        },
        meta: ["(I used linguine)"],
        name: "pasta",
        original: "6-8 ounces pasta (I used linguine)",
        originalName: "pasta (I used linguine)",
        unit: "ounces",
      },
      {
        aisle: "Spices and Seasonings",
        amount: 2.0,
        consitency: "solid",
        id: 1032009,
        image: "red-pepper-flakes.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "pinches",
            unitShort: "pinches",
          },
          us: {
            amount: 2.0,
            unitLong: "pinches",
            unitShort: "pinches",
          },
        },
        meta: ["red"],
        name: "red pepper flakes",
        original: "couple of pinches red pepper flakes, optional",
        originalName: "couple of red pepper flakes, optional",
        unit: "pinches",
      },
      {
        aisle: "Spices and Seasonings",
        amount: 2.0,
        consitency: "solid",
        id: 1102047,
        image: "salt-and-pepper.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "servings",
            unitShort: "servings",
          },
          us: {
            amount: 2.0,
            unitLong: "servings",
            unitShort: "servings",
          },
        },
        meta: ["to taste"],
        name: "salt and pepper",
        original: "salt and pepper, to taste",
        originalName: "salt and pepper, to taste",
        unit: "servings",
      },
      {
        aisle: "Produce",
        amount: 3.0,
        consitency: "solid",
        id: 11291,
        image: "spring-onions.jpg",
        measures: {
          metric: {
            amount: 3.0,
            unitLong: "",
            unitShort: "",
          },
          us: {
            amount: 3.0,
            unitLong: "",
            unitShort: "",
          },
        },
        meta: ["white", "green", "separated", "chopped"],
        name: "scallions",
        original: "3 scallions, chopped, white and green parts separated",
        originalName: "scallions, chopped, white and green parts separated",
        unit: "",
      },
      {
        aisle: "Alcoholic Beverages",
        amount: 2.0,
        consitency: "liquid",
        id: 14106,
        image: "white-wine.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
          us: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
        },
        meta: ["white"],
        name: "white wine",
        original: "2-3 tbsp white wine",
        originalName: "white wine",
        unit: "tbsp",
      },
      {
        aisle: "Pasta and Rice",
        amount: 0.25,
        consitency: "solid",
        id: 99025,
        image: "breadcrumbs.jpg",
        measures: {
          metric: {
            amount: 59.147,
            unitLong: "milliliters",
            unitShort: "ml",
          },
          us: {
            amount: 0.25,
            unitLong: "cups",
            unitShort: "cups",
          },
        },
        meta: ["whole wheat", "(I used panko)"],
        name: "whole wheat bread crumbs",
        original: "1/4 cup whole wheat bread crumbs (I used panko)",
        originalName: "whole wheat bread crumbs (I used panko)",
        unit: "cup",
      },
    ],
    summary:
      'Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs might be a good recipe to expand your main course repertoire. One portion of this dish contains approximately <b>19g of protein </b>,  <b>20g of fat </b>, and a total of  <b>584 calories </b>. For  <b>$1.63 per serving </b>, this recipe  <b>covers 23% </b> of your daily requirements of vitamins and minerals. This recipe serves 2. It is brought to you by fullbellysisters.blogspot.com. 209 people were glad they tried this recipe. A mixture of scallions, salt and pepper, white wine, and a handful of other ingredients are all it takes to make this recipe so scrumptious. From preparation to the plate, this recipe takes approximately  <b>45 minutes </b>. All things considered, we decided this recipe  <b>deserves a spoonacular score of 83% </b>. This score is awesome. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/cauliflower-gratin-with-garlic-breadcrumbs-318375">Cauliflower Gratin with Garlic Breadcrumbs</a>, < href="https://spoonacular.com/recipes/pasta-with-cauliflower-sausage-breadcrumbs-30437">Pasta With Cauliflower, Sausage, & Breadcrumbs</a>, and <a href="https://spoonacular.com/recipes/pasta-with-roasted-cauliflower-parsley-and-breadcrumbs-30738">Pasta With Roasted Cauliflower, Parsley, And Breadcrumbs</a>.',
    winePairing: {
      pairedWines: ["chardonnay", "gruener veltliner", "sauvignon blanc"],
      pairingText:
        "Chardonnay, Gruener Veltliner, and Sauvignon Blanc are great choices for Pasta. Sauvignon Blanc and Gruner Veltliner both have herby notes that complement salads with enough acid to match tart vinaigrettes, while a Chardonnay can be a good pick for creamy salad dressings. The Buddha Kat Winery Chardonnay with a 4 out of 5 star rating seems like a good match. It costs about 25 dollars per bottle.",
      productMatches: [
        {
          id: 469199,
          title: "Buddha Kat Winery Chardonnay",
          description:
            "We barrel ferment our Chardonnay and age it in a mix of Oak and Stainless. Giving this light bodied wine modest oak character, a delicate floral aroma, and a warming finish.",
          price: "$25.0",
          imageUrl: "https://spoonacular.com/productImages/469199-312x231.jpg",
          averageRating: 0.8,
          ratingCount: 1.0,
          score: 0.55,
          link:
            "https://www.amazon.com/2015-Buddha-Kat-Winery-Chardonnay/dp/B00OSAVVM4?tag=spoonacular-20",
        },
      ],
    },
  };
};
export const getExampleRecipes = () => [
  {
    id: 551111,
    title: "Marbled Strawberry Parfait",
    image: "https://spoonacular.com/recipeImages/551111-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 9316,
        amount: 500.0,
        unit: "g",
        unitLong: "grams",
        unitShort: "g",
        aisle: "Produce",
        name: "strawberries",
        original: "1 pound (500 g) fresh strawberries",
        originalString: "1 pound (500 g) fresh strawberries",
        originalName: "pound fresh strawberries",
        metaInformation: ["fresh"],
        meta: ["fresh"],
        extendedName: "fresh strawberries",
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/strawberries.png",
      },
      {
        id: 1001053,
        amount: 100.0,
        unit: "ml",
        unitLong: "milliliters",
        unitShort: "ml",
        aisle: "Milk, Eggs, Other Dairy",
        name: "whipping cream",
        original: "1/2 cup (100 ml) whipping cream",
        originalString: "1/2 cup (100 ml) whipping cream",
        originalName: "1/2 cup whipping cream",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/fluid-cream.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 93820,
        amount: 250.0,
        unit: "g",
        unitLong: "grams",
        unitShort: "g",
        aisle: "Cheese",
        name: "mascarpone",
        original: "9 0z (250 g) mascarpone",
        originalString: "9 0z (250 g) mascarpone",
        originalName: "0z mascarpone",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 24,
  },
  {
    id: 68613,
    title: "Cannoli Filling",
    image: "https://spoonacular.com/recipeImages/68613-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 93630,
        amount: 0.75,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Cheese",
        name: "skim milk ricotta cheese",
        original: "3/4 cup Whole Milk Ricotta Cheese",
        originalString: "3/4 cup Whole Milk Ricotta Cheese",
        originalName: "Whole Milk Ricotta Cheese",
        metaInformation: ["whole"],
        meta: ["whole"],
        extendedName: "whole skim milk ricotta cheese",
        image: "https://spoonacular.com/cdn/ingredients_100x100/ricotta.png",
      },
      {
        id: 2050,
        amount: 0.75,
        unit: "tsp",
        unitLong: "teaspoons",
        unitShort: "tsp",
        aisle: "Baking",
        name: "vanilla",
        original: "3/4 tsp Vanilla",
        originalString: "3/4 tsp Vanilla",
        originalName: "Vanilla",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/vanilla.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 93820,
        amount: 8.0,
        unit: "oz",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Cheese",
        name: "mascarpone cheese",
        original: "8 oz Mascarpone Cheese",
        originalString: "8 oz Mascarpone Cheese",
        originalName: "Mascarpone Cheese",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 18,
  },
  {
    id: 84221,
    title: "Mascarpone Cream With Vinsanto",
    image: "https://spoonacular.com/recipeImages/84221-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 19165,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Baking",
        name: "cocoa powder",
        original: "unsweetened cocoa powder to serve",
        originalString: "unsweetened cocoa powder to serve",
        originalName: "unsweetened cocoa powder to serve",
        metaInformation: ["unsweetened"],
        meta: ["unsweetened"],
        extendedName: "unsweetened cocoa powder",
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/cocoa-powder.png",
      },
      {
        id: 1123,
        amount: 5.0,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Milk, Eggs, Other Dairy",
        name: "eggs",
        original: "5 eggs, yolks and whites separated",
        originalString: "5 eggs, yolks and whites separated",
        originalName: "eggs, yolks and whites separated",
        metaInformation: ["separated"],
        meta: ["separated"],
        image: "https://spoonacular.com/cdn/ingredients_100x100/egg.png",
      },
    ],
    usedIngredients: [
      {
        id: 93820,
        amount: 1.0,
        unit: "kg",
        unitLong: "kg",
        unitShort: "kg",
        aisle: "Cheese",
        name: "mascarpone cheese",
        original: "1 kg of mascarpone cheese",
        originalString: "1 kg of mascarpone cheese",
        originalName: "mascarpone cheese",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 11,
  },
  {
    id: 50451,
    title: "Blackberry Puffs",
    image: "https://spoonacular.com/recipeImages/50451-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 9042,
        amount: 12.0,
        unit: "ozs",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Produce",
        name: "blackberries",
        original: "3 cups blackberries (12 ozs)",
        originalString: "3 cups blackberries (12 ozs)",
        originalName: "cups blackberries",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/blackberries.jpg",
      },
      {
        id: 18337,
        amount: 1.0,
        unit: "sheet",
        unitLong: "sheet",
        unitShort: "sheet",
        aisle: "Refrigerated;Frozen",
        name: "puff pastry",
        original: "1 sheet puff pastry (1/2 of a 17.3-oz package)",
        originalString: "1 sheet puff pastry (1/2 of a 17.3-oz package)",
        originalName: "puff pastry (1/2 of a 17.3-oz package)",
        metaInformation: ["()"],
        meta: ["()"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/puff-pastry.png",
      },
    ],
    usedIngredients: [
      {
        id: 93820,
        amount: 0.75,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Cheese",
        name: "mascarpone cheese",
        original: "3/4 cup mascarpone cheese",
        originalString: "3/4 cup mascarpone cheese",
        originalName: "mascarpone cheese",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 4,
  },
  {
    id: 298171,
    title: "Limoncello Granita",
    image: "https://spoonacular.com/recipeImages/298171-312x231.jpeg",
    imageType: "jpeg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 9156,
        amount: 1.0,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Produce",
        name: "lemon zest",
        original: "1 lemon, zested and juiced",
        originalString: "1 lemon, zested and juiced",
        originalName: "lemon, zested and juiced",
        metaInformation: ["juiced"],
        meta: ["juiced"],
        image: "https://spoonacular.com/cdn/ingredients_100x100/zest-lemon.jpg",
      },
      {
        id: 99021,
        amount: 0.5,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Alcoholic Beverages",
        name: "limoncello",
        original: "1/2 cup limoncello liqueur",
        originalString: "1/2 cup limoncello liqueur",
        originalName: "limoncello liqueur",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/limoncello.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 93820,
        amount: 8.0,
        unit: "ounces",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Cheese",
        name: "mascarpone cheese",
        original: "1 cup (8 ounces) mascarpone cheese, at room temperature",
        originalString:
          "1 cup (8 ounces) mascarpone cheese, at room temperature",
        originalName: "cup mascarpone cheese, at room temperature",
        metaInformation: ["at room temperature"],
        meta: ["at room temperature"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 2,
  },
  {
    id: 58417,
    title: "Strawberries And Cinnamon Mascarpone",
    image: "https://spoonacular.com/recipeImages/58417-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 1012010,
        amount: 2.0,
        unit: "servings",
        unitLong: "servings",
        unitShort: "servings",
        aisle: "Spices and Seasonings",
        name: "ground cinnamon",
        original: "ground cinnamon",
        originalString: "ground cinnamon",
        originalName: "ground cinnamon",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/cinnamon.jpg",
      },
      {
        id: 9316,
        amount: 500.0,
        unit: "g",
        unitLong: "grams",
        unitShort: "g",
        aisle: "Produce",
        name: "strawberries",
        original: "500 g strawberries, washed",
        originalString: "500 g strawberries, washed",
        originalName: "strawberries, washed",
        metaInformation: ["washed"],
        meta: ["washed"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/strawberries.png",
      },
    ],
    usedIngredients: [
      {
        id: 93820,
        amount: 250.0,
        unit: "g",
        unitLong: "grams",
        unitShort: "g",
        aisle: "Cheese",
        name: "mascarpone cheese",
        original: "250 g mascarpone cheese",
        originalString: "250 g mascarpone cheese",
        originalName: "mascarpone cheese",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 0,
  },
  {
    id: 67551,
    title: "Chocolate, Cream And Mascarpone Trifle",
    image: "https://spoonacular.com/recipeImages/67551-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 19081,
        amount: 3.0,
        unit: "servings",
        unitLong: "servings",
        unitShort: "servings",
        aisle: "Sweet Snacks",
        name: "chocolate",
        original: "dark chocolate flakes",
        originalString: "dark chocolate flakes",
        originalName: "dark chocolate flakes",
        metaInformation: ["dark"],
        meta: ["dark"],
        extendedName: "dark chocolate",
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/milk-chocolate.jpg",
      },
      {
        id: 1001053,
        amount: 1.0,
        unit: "large",
        unitLong: "large",
        unitShort: "large",
        aisle: "Milk, Eggs, Other Dairy",
        name: "whipping cream",
        original:
          "whipping cream (I used 250 ml of cream, enough to make two large bowl of trifle)",
        originalString:
          "whipping cream (I used 250 ml of cream, enough to make two large bowl of trifle)",
        originalName:
          "whipping cream (I used 250 ml of cream, enough to make two bowl of trifle)",
        metaInformation: [
          "(I used 250 ml of cream, enough to make two large bowl of trifle)",
        ],
        meta: [
          "(I used 250 ml of cream, enough to make two large bowl of trifle)",
        ],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/fluid-cream.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 93820,
        amount: 3.0,
        unit: "servings",
        unitLong: "servings",
        unitShort: "servings",
        aisle: "Cheese",
        name: "mascarpone cheese",
        original:
          "mascarpone cheese, a creamy and mild cheese (same quantity as cream)",
        originalString:
          "mascarpone cheese, a creamy and mild cheese (same quantity as cream)",
        originalName:
          "mascarpone cheese, a creamy and mild cheese (same quantity as cream)",
        metaInformation: ["(same quantity as cream)"],
        meta: ["(same quantity as cream)"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 0,
  },
  {
    id: 371000,
    title: "Prosciutto-Wrapped Apricots",
    image: "https://spoonacular.com/recipeImages/371000-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 9021,
        amount: 7.0,
        unit: "ounces",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Produce",
        name: "apricots",
        original: "1 package (7 ounces) dried pitted Mediterranean apricots",
        originalString:
          "1 package (7 ounces) dried pitted Mediterranean apricots",
        originalName: "package dried pitted Mediterranean apricots",
        metaInformation: ["dried", "pitted"],
        meta: ["dried", "pitted"],
        extendedName: "dried apricots",
        image: "https://spoonacular.com/cdn/ingredients_100x100/apricot.jpg",
      },
      {
        id: 10010123,
        amount: 12.0,
        unit: "slices",
        unitLong: "slices",
        unitShort: "slice",
        aisle: "Meat",
        name: "prosciutto",
        original: "12 thin slices prosciutto",
        originalString: "12 thin slices prosciutto",
        originalName: "12 thin slices prosciutto",
        metaInformation: ["thin"],
        meta: ["thin"],
        image: "https://spoonacular.com/cdn/ingredients_100x100/proscuitto.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 93820,
        amount: 0.75,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Cheese",
        name: "mascarpone cheese",
        original: "3/4 cup Mascarpone cheese",
        originalString: "3/4 cup Mascarpone cheese",
        originalName: "Mascarpone cheese",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 0,
  },
];
