export const getExampleRecipes = () => [
  {
    id: 551111,
    title: "Marbled Strawberry Parfait",
    image: "https://spoonacular.com/recipeImages/551111-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 9316,
        amount: 500.0,
        unit: "g",
        unitLong: "grams",
        unitShort: "g",
        aisle: "Produce",
        name: "strawberries",
        original: "1 pound (500 g) fresh strawberries",
        originalString: "1 pound (500 g) fresh strawberries",
        originalName: "pound fresh strawberries",
        metaInformation: ["fresh"],
        meta: ["fresh"],
        extendedName: "fresh strawberries",
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/strawberries.png",
      },
      {
        id: 1001053,
        amount: 100.0,
        unit: "ml",
        unitLong: "milliliters",
        unitShort: "ml",
        aisle: "Milk, Eggs, Other Dairy",
        name: "whipping cream",
        original: "1/2 cup (100 ml) whipping cream",
        originalString: "1/2 cup (100 ml) whipping cream",
        originalName: "1/2 cup whipping cream",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/fluid-cream.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 93820,
        amount: 250.0,
        unit: "g",
        unitLong: "grams",
        unitShort: "g",
        aisle: "Cheese",
        name: "mascarpone",
        original: "9 0z (250 g) mascarpone",
        originalString: "9 0z (250 g) mascarpone",
        originalName: "0z mascarpone",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 24,
  },
  {
    id: 68613,
    title: "Cannoli Filling",
    image: "https://spoonacular.com/recipeImages/68613-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 93630,
        amount: 0.75,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Cheese",
        name: "skim milk ricotta cheese",
        original: "3/4 cup Whole Milk Ricotta Cheese",
        originalString: "3/4 cup Whole Milk Ricotta Cheese",
        originalName: "Whole Milk Ricotta Cheese",
        metaInformation: ["whole"],
        meta: ["whole"],
        extendedName: "whole skim milk ricotta cheese",
        image: "https://spoonacular.com/cdn/ingredients_100x100/ricotta.png",
      },
      {
        id: 2050,
        amount: 0.75,
        unit: "tsp",
        unitLong: "teaspoons",
        unitShort: "tsp",
        aisle: "Baking",
        name: "vanilla",
        original: "3/4 tsp Vanilla",
        originalString: "3/4 tsp Vanilla",
        originalName: "Vanilla",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/vanilla.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 93820,
        amount: 8.0,
        unit: "oz",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Cheese",
        name: "mascarpone cheese",
        original: "8 oz Mascarpone Cheese",
        originalString: "8 oz Mascarpone Cheese",
        originalName: "Mascarpone Cheese",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 18,
  },
  {
    id: 84221,
    title: "Mascarpone Cream With Vinsanto",
    image: "https://spoonacular.com/recipeImages/84221-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 19165,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Baking",
        name: "cocoa powder",
        original: "unsweetened cocoa powder to serve",
        originalString: "unsweetened cocoa powder to serve",
        originalName: "unsweetened cocoa powder to serve",
        metaInformation: ["unsweetened"],
        meta: ["unsweetened"],
        extendedName: "unsweetened cocoa powder",
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/cocoa-powder.png",
      },
      {
        id: 1123,
        amount: 5.0,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Milk, Eggs, Other Dairy",
        name: "eggs",
        original: "5 eggs, yolks and whites separated",
        originalString: "5 eggs, yolks and whites separated",
        originalName: "eggs, yolks and whites separated",
        metaInformation: ["separated"],
        meta: ["separated"],
        image: "https://spoonacular.com/cdn/ingredients_100x100/egg.png",
      },
    ],
    usedIngredients: [
      {
        id: 93820,
        amount: 1.0,
        unit: "kg",
        unitLong: "kg",
        unitShort: "kg",
        aisle: "Cheese",
        name: "mascarpone cheese",
        original: "1 kg of mascarpone cheese",
        originalString: "1 kg of mascarpone cheese",
        originalName: "mascarpone cheese",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 11,
  },
  {
    id: 50451,
    title: "Blackberry Puffs",
    image: "https://spoonacular.com/recipeImages/50451-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 9042,
        amount: 12.0,
        unit: "ozs",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Produce",
        name: "blackberries",
        original: "3 cups blackberries (12 ozs)",
        originalString: "3 cups blackberries (12 ozs)",
        originalName: "cups blackberries",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/blackberries.jpg",
      },
      {
        id: 18337,
        amount: 1.0,
        unit: "sheet",
        unitLong: "sheet",
        unitShort: "sheet",
        aisle: "Refrigerated;Frozen",
        name: "puff pastry",
        original: "1 sheet puff pastry (1/2 of a 17.3-oz package)",
        originalString: "1 sheet puff pastry (1/2 of a 17.3-oz package)",
        originalName: "puff pastry (1/2 of a 17.3-oz package)",
        metaInformation: ["()"],
        meta: ["()"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/puff-pastry.png",
      },
    ],
    usedIngredients: [
      {
        id: 93820,
        amount: 0.75,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Cheese",
        name: "mascarpone cheese",
        original: "3/4 cup mascarpone cheese",
        originalString: "3/4 cup mascarpone cheese",
        originalName: "mascarpone cheese",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 4,
  },
  {
    id: 298171,
    title: "Limoncello Granita",
    image: "https://spoonacular.com/recipeImages/298171-312x231.jpeg",
    imageType: "jpeg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 9156,
        amount: 1.0,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Produce",
        name: "lemon zest",
        original: "1 lemon, zested and juiced",
        originalString: "1 lemon, zested and juiced",
        originalName: "lemon, zested and juiced",
        metaInformation: ["juiced"],
        meta: ["juiced"],
        image: "https://spoonacular.com/cdn/ingredients_100x100/zest-lemon.jpg",
      },
      {
        id: 99021,
        amount: 0.5,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Alcoholic Beverages",
        name: "limoncello",
        original: "1/2 cup limoncello liqueur",
        originalString: "1/2 cup limoncello liqueur",
        originalName: "limoncello liqueur",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/limoncello.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 93820,
        amount: 8.0,
        unit: "ounces",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Cheese",
        name: "mascarpone cheese",
        original: "1 cup (8 ounces) mascarpone cheese, at room temperature",
        originalString:
          "1 cup (8 ounces) mascarpone cheese, at room temperature",
        originalName: "cup mascarpone cheese, at room temperature",
        metaInformation: ["at room temperature"],
        meta: ["at room temperature"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 2,
  },
  {
    id: 58417,
    title: "Strawberries And Cinnamon Mascarpone",
    image: "https://spoonacular.com/recipeImages/58417-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 1012010,
        amount: 2.0,
        unit: "servings",
        unitLong: "servings",
        unitShort: "servings",
        aisle: "Spices and Seasonings",
        name: "ground cinnamon",
        original: "ground cinnamon",
        originalString: "ground cinnamon",
        originalName: "ground cinnamon",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/cinnamon.jpg",
      },
      {
        id: 9316,
        amount: 500.0,
        unit: "g",
        unitLong: "grams",
        unitShort: "g",
        aisle: "Produce",
        name: "strawberries",
        original: "500 g strawberries, washed",
        originalString: "500 g strawberries, washed",
        originalName: "strawberries, washed",
        metaInformation: ["washed"],
        meta: ["washed"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/strawberries.png",
      },
    ],
    usedIngredients: [
      {
        id: 93820,
        amount: 250.0,
        unit: "g",
        unitLong: "grams",
        unitShort: "g",
        aisle: "Cheese",
        name: "mascarpone cheese",
        original: "250 g mascarpone cheese",
        originalString: "250 g mascarpone cheese",
        originalName: "mascarpone cheese",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 0,
  },
  {
    id: 67551,
    title: "Chocolate, Cream And Mascarpone Trifle",
    image: "https://spoonacular.com/recipeImages/67551-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 19081,
        amount: 3.0,
        unit: "servings",
        unitLong: "servings",
        unitShort: "servings",
        aisle: "Sweet Snacks",
        name: "chocolate",
        original: "dark chocolate flakes",
        originalString: "dark chocolate flakes",
        originalName: "dark chocolate flakes",
        metaInformation: ["dark"],
        meta: ["dark"],
        extendedName: "dark chocolate",
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/milk-chocolate.jpg",
      },
      {
        id: 1001053,
        amount: 1.0,
        unit: "large",
        unitLong: "large",
        unitShort: "large",
        aisle: "Milk, Eggs, Other Dairy",
        name: "whipping cream",
        original:
          "whipping cream (I used 250 ml of cream, enough to make two large bowl of trifle)",
        originalString:
          "whipping cream (I used 250 ml of cream, enough to make two large bowl of trifle)",
        originalName:
          "whipping cream (I used 250 ml of cream, enough to make two bowl of trifle)",
        metaInformation: [
          "(I used 250 ml of cream, enough to make two large bowl of trifle)",
        ],
        meta: [
          "(I used 250 ml of cream, enough to make two large bowl of trifle)",
        ],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/fluid-cream.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 93820,
        amount: 3.0,
        unit: "servings",
        unitLong: "servings",
        unitShort: "servings",
        aisle: "Cheese",
        name: "mascarpone cheese",
        original:
          "mascarpone cheese, a creamy and mild cheese (same quantity as cream)",
        originalString:
          "mascarpone cheese, a creamy and mild cheese (same quantity as cream)",
        originalName:
          "mascarpone cheese, a creamy and mild cheese (same quantity as cream)",
        metaInformation: ["(same quantity as cream)"],
        meta: ["(same quantity as cream)"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 0,
  },
  {
    id: 371000,
    title: "Prosciutto-Wrapped Apricots",
    image: "https://spoonacular.com/recipeImages/371000-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 9021,
        amount: 7.0,
        unit: "ounces",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Produce",
        name: "apricots",
        original: "1 package (7 ounces) dried pitted Mediterranean apricots",
        originalString:
          "1 package (7 ounces) dried pitted Mediterranean apricots",
        originalName: "package dried pitted Mediterranean apricots",
        metaInformation: ["dried", "pitted"],
        meta: ["dried", "pitted"],
        extendedName: "dried apricots",
        image: "https://spoonacular.com/cdn/ingredients_100x100/apricot.jpg",
      },
      {
        id: 10010123,
        amount: 12.0,
        unit: "slices",
        unitLong: "slices",
        unitShort: "slice",
        aisle: "Meat",
        name: "prosciutto",
        original: "12 thin slices prosciutto",
        originalString: "12 thin slices prosciutto",
        originalName: "12 thin slices prosciutto",
        metaInformation: ["thin"],
        meta: ["thin"],
        image: "https://spoonacular.com/cdn/ingredients_100x100/proscuitto.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 93820,
        amount: 0.75,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Cheese",
        name: "mascarpone cheese",
        original: "3/4 cup Mascarpone cheese",
        originalString: "3/4 cup Mascarpone cheese",
        originalName: "Mascarpone cheese",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-cream-fluffy.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 0,
  },
];
